### ISSUE TITLE
Implement the device finder

### ISSUE THREAD

**Issue by lu-w** [fRandOmizer/DISII-Project#12]
Implement a _DeviceFinder_ class that searches for devices according to the current position of the smartphone.
The _DeviceFinder_ should be able to register objects that want to be informed when the list of devices that the smartphone points to changes (Thus, implement an interface _DeviceListDelegate_ that has a method _delegateDeviceList(List<DeviceProxy> devices)_ which is called by the _DeviceFinder_ for every registered object on every change of the device list). The _DeviceProxy_ class was implemented by Christoph and represents one device.
The position of the device is defined by the cardinal direction. Every device should store its cardinal direction, and its z-axis as an integer (which represent the spatial order of the devices in case one device is behind another). Feel free to implement this.
The device finder should be basically a thread that polls the compass every x ms and and iterates through every device and constructs the list of devices the smartphone points to. If the list has changed, it should push this information to every _DeviceListDelegate_.

**Comment by ChristophRichter92** [comment]
sry wrong commit nr :D it should close #13
